# Generated by Django 3.2.7 on 2021-09-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='DEFAULT VALUE', max_length=140, upload_to='images'),
        ),
    ]
